name: Enforce Specific Reviewer Approvals

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]

jobs:
  enforce_approvals:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Required Approvals
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Required reviewers
          REQUIRED_REVIEWER="matx104"
          SYSOPS_TEAM=("WamiqSid" "Aatika-K")

          # Get the pull request number
          PR_NUMBER=$(jq -r .pull_request.number "$GITHUB_EVENT_PATH")

          # Get the list of reviewers who have approved the PR
          APPROVED_REVIEWERS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/reviews" \
            | jq -r '.[] | select(.state == "APPROVED") | .user.login')

          # Set up a flag for each required reviewer
          REQUIRED_APPROVED=0
          SYSOPS_APPROVED=0

          # Check if each required reviewer has approved
          for reviewer in $APPROVED_REVIEWERS; do
            if [[ "$reviewer" == "$REQUIRED_REVIEWER" ]]; then
              REQUIRED_APPROVED=1
            elif [[ "${SYSOPS_TEAM[@]}" =~ "$reviewer" ]]; then
              SYSOPS_APPROVED=1
            fi
          done

          # Check if the necessary approvals are met
          if [[ $REQUIRED_APPROVED -eq 1 && $SYSOPS_APPROVED -eq 1 ]]; then
            echo "All required reviewers have approved."
          else
            echo "Error: Approval from matx104 and one SysOps team member is required."
            exit 1
          fi
